// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Find(arg1:string):Promise<main.Service>;

export function Install(arg1:main.Service):Promise<Error>;

export function Pause(arg1:string):Promise<Error>;

export function Remove(arg1:string):Promise<Error>;

export function SelectExecutable(arg1:string):Promise<string>;

export function Start(arg1:string):Promise<Error>;

export function Stop(arg1:string):Promise<Error>;

export function Update(arg1:main.Service):Promise<Error>;
