// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['main']['App']['Create'](arg1);
}

export function Find(arg1) {
  return window['go']['main']['App']['Find'](arg1);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}
